project_id = "pjcfncnydhxrlnaowbae"

[functions.ai-assistant]
verify_jwt = false

[functions.send-monthly-reports]
verify_jwt = false

[functions.update-exchange-rates]
verify_jwt = false

[functions.webhooks-google-forms]
verify_jwt = false
